### ISSUE TITLE
support for 1080p video

### ISSUE THREAD

**Issue by williamjames1** [weiliu89/caffe#15]
Hi,
I would like to use this for 1080p video. what changes I need to do in config file?
I have to train on my own data set as well.
Any idea about fps? assuming 4-5 objects in an image.

Thanks.
william. j.

**Comment by weiliu89** [comment]
Please refer to data/VOC0712, data/MSCOCO or data/ILSVRC on how to prepare the dataset, and examples/ssd/ssd_pascal.py on how to create and train a model.

The reason that SSD is fast and has similar quality as Faster R-CNN is because it spreads out default box to multiple feature maps and thus can do detection on small image size (300 x 300), making it extremely fast. 88% of the time is spent on the base network (aka VGG16). So if you increase the size of image, the time would be roughly linearly increase as well.

**Comment by williamjames1** [comment]
Hi Wei,
Thanks.  Do you have any idea about the other base network which would improve performance.
My requirement is that I should be able to process 1080 Video @30 fps for object detection with GPU memory around 3GB. 
Thanks.
william. j.
