### ISSUE TITLE
Detecting small objects ...

### ISSUE THREAD

**Issue by VanitarNordic** [weiliu89/caffe#453]
Does SSD (SSD300) is suitable to detect small objects? for example `20*20` object inside `1024*768` image.

What modifications should be done to satisfy this challenge?

**Comment by weiliu89** [comment]
Increase image size

**Comment by VanitarNordic** [comment]
you mean `300*300` to something bigger? it would not satisfy the speed?

**Comment by weiliu89** [comment]
Yes. It is a tradeoff between accuracy and speed.

**Comment by VanitarNordic** [comment]
Thank you very much

**Comment by RoseLii** [comment]
please help me.I am detect small object,but i have image of 1360*800 size.I I did not seem to converge when I was trained. What should I do so that it can converge。
 @VanitarNordic @weiliu89

**Comment by RoseLii** [comment]
@VanitarNordic  @weiliu89 帮帮我。
我之前在训练的时候出现Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_conf'; shape mismatch. Source param shape is 84 512 3 3 (387072); target param shape is 176 512 3 3 (811008). To learn this layer's parameters from scratch rather than copying from a saved net, rename the laye.这样的错误，我确定我的num_class都已经改成我自己的类，但是还是出错。我找到其他的解决方法
mbox_layers = CreateMultiBoxHead(net, data_layer='data', from_layers=mbox_source_layers,
        use_batchnorm=use_batchnorm, min_sizes=min_sizes, max_sizes=max_sizes,
        aspect_ratios=aspect_ratios, steps=steps, normalizations=normalizations,
        num_classes=num_classes, share_location=share_location, flip=flip, clip=clip,
        prior_variance=prior_variance, kernel_size=3, pad=1, lr_mult=lr_mult,conf_postfix='_kitti')
就是多加了一个,conf_postfix='_kitti'，训练是可以了，但是这样好像是跳过conv4-3.后来我在看的时候发现conv4-3对小目标检测是非常有用的。请问有没有好的办法解决conv4_3_norm_mbox_conf这个问题。并且对于小目标检测是不是效果不太好呀。我已经训练好久但是一直不收敛。有什么好的方法吗？拜托拜托。

**Comment by www322** [comment]
> Yes. It is a tradeoff between accuracy and speed.

hi, for small objects, my model successfully detects it, but the location always has a right offset, can you help me analysis it, thanks very much!
