### ISSUE TITLE
About matching strategy

### ISSUE THREAD

**Issue by wk910930** [weiliu89/caffe#555]
Dear @weiliu89 ,

When introducing the **Matching strategy** in the paper, it says

> We begin by matching each ground truth box to the default box with the best
> jaccard overlap (as in MultiBox [7]). Unlike MultiBox, we then match default boxes to
> any ground truth with jaccard overlap higher than a threshold (0.5). 

I just cannot figure out why would we need to do the 'begin' part. Actually we just need to do the 'then' part: match each prior box to its best satisfied (*i.e.* biggest overlap) ground truth bounding box and assign according class label, right? By this we can guarantee each prior box only matches a single ground truth object and each ground truth object might cover several prior boxes. And what if there is no prior box matches some ground truth objects (for some ground truth objects might have rare ratios)?

In simple, I have two questions:
1. Do we need (especially in the implementation) to to the 'begin' part in the above quote?
2. What if some ground truth box cannot find proper prior boxes?

Sorry if I am missing something.

Thanks!
Kun

**Comment by pierluigiferrari** [comment]
I think you mixed up the 'begin' part and the 'then' part in your own description.

1. You need what you call the 'begin' to ensure that a given ground truth box will be matched to **at least one** prior box. This first part matches a ground truth box to whatever prior box with which it has the highest Jaccard overlap, regardless how low that Jaccard overlap is. This way you are certain to get at least one match even if no prior box exceeds the threshold Jaccard overlap with the given ground truth box. The highest overlap could be 0.03 while the set threshold is 0.5.
2. That cannot happen because of 1.

The 'then' part matches all priors that have a Jaccard overlap higher than the threshold in addition to that one match that we already have for sure.

You could also do the two steps in reverse order by the way, it wouldn't matter. You could first match all priors with a Jaccard overlap higher than the threshold and only if this step yields zero matches, then do the other step and match the prior with the highest overlap.

**Comment by wk910930** [comment]
@pierluigiferrari , thanks for your great answer! Just to be sure, what if we use the sparse prior boxes instead of dense version used in paper? If a given ground truth box cannot find any prior box that has overlap with, the program will crash (or some other bad things will happen), right? In others words, we must guarantee each ground truth box will be matched to **at least one** prior box, right?

**Comment by wk910930** [comment]
I found a wonderful conversation in https://github.com/weiliu89/caffe/issues/200, which might talks about the similar questions. What do you think, @pierluigiferrari ?
