### ISSUE TITLE
What was the cause of change of mAP from 74% to 77%?

### ISSUE THREAD

**Issue by sfraczek** [weiliu89/caffe#705]
Hi, we are porting ssd to aeon+neon and we have reached 74% threshold that was reported by you previously. Could you please shed some light on what exactly was the cause of change in accuracy between those two updates?

**Comment by sfraczek** [comment]
Oh, sorry I just found the footnote in paper telling it is explained in Section 3.6.

**Comment by RoseLii** [comment]
please help me
Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_conf'; shape mismatch.  Source param shape is 84 512 3 3 (387072); target param shape is 176 512 3 3 (811008). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
