### ISSUE TITLE
What' the meaning of permute and flatten in CreateMultiboxHead ?

### ISSUE THREAD

**Issue by youngwanLEE** [weiliu89/caffe#85]
Hi Wei, 

Although I read your SSD paper over and over again, I could not fully understand your code due to my shortage knowledge.

1. 
I want know how convolutional classifier works instead of fully connected layer. I guessed classification job happens in CreateMutiBoxHead. 

2. 
 I want to know permute and flatten layers's meaning and role for the classification step in creating location and confidence prediction layers, after ConvBNLayer.

Thanks

**Comment by weiliu89** [comment]
- [Here](https://github.com/weiliu89/caffe/blob/ssd/python/caffe/model_libs.py#L641-L652) and [here](https://github.com/weiliu89/caffe/blob/ssd/python/caffe/model_libs.py#L654-L663) describes how the loc and conf predictions are generated using 3 x 3 Convolution layer.

- permute layer is used to make it easier to combine predictions from different layers by changing from N x C x H x W to N x H x W x C so that the first C elements are predictions at position (0, 0), and the second C elements are for (0, 1) etc. What's more, because predictions from different layer are of different spatial resolution, I use flatten to make it N x HWC x 1 x 1 so that it is easy to combine. These are some implementation (engineering) details, which are ignored in the paper.

**Comment by youngwanLEE** [comment]
oh thank you very much!

**Comment by Anhaoxu** [comment]
@youngwanLEE @weiliu89 I can't understand why say "the first C elements are predictions at position (0, 0), and the second C elements are for (0, 1) etc" and "I use flatten to make it N x HWC x 1 x 1 so that it is easy to combine. ". permute layer is want to change the order of blobs? and why say flatten can make it easy for combine? if I just not flatten it, it is difficult do that?

**Comment by Tveek** [comment]
@Anhaoxu C is num output of previous conv layer, which has certain specific meanings。For example, conv7(fc7) layer's default box number is 6, so in location branch ,C is 6x4=24, but in confidence branch with VOC dataset, C is 6x(20+1)=126;Through permute layer,in location branch,conv7(fc7)'s output shape is N x H x W x 24,thus ,(0,1),(0,1) etc,which is the position of featrue map(from (0,0) to (h,w));so the first C elements are predictions at position (0, 0)。For your second question,the input of dection layer come from different previous layer,like conv4_3,conv7(fc7) and so on, those layer's output shape are different  except batch size dimension;Thus,before Concat,you need flatten to N x HWC x 1 x 1,and you can also interpreted this concat layer as combining information from different level feature map.
