### ISSUE TITLE
training failed

### ISSUE THREAD

**Issue by EvergreenHZ** [weiliu89/caffe#878]
Hi, I am trying to train my own model (to recognize BMW and Ford logos), unfortunately, I come across this problem:
`F0331 13:22:59.984701 11025 net.cpp:774] Cannot copy param 0 weights from layer 'conv4_3_norm_mbox_conf'; shape mismatch.  Source param shape is 84 512 3 3 (387072); target param shape is 12 512 3 3 (55296). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
*** Check failure stack trace: ***
    @     0x7fa4a1cdc5cd  google::LogMessage::Fail()
    @     0x7fa4a1cde433  google::LogMessage::SendToLog()
    @     0x7fa4a1cdc15b  google::LogMessage::Flush()
    @     0x7fa4a1cdee1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa4a251602b  caffe::Net<>::CopyTrainedLayersFrom()
    @     0x7fa4a253fc3b  caffe::SGDSolver<>::RestoreSolverStateFromBinaryProto()
    @     0x7fa4a246a2f7  caffe::Solver<>::Restore()
    @           0x40cdc4  train()
    @           0x408908  main
    @     0x7fa4a0408830  __libc_start_main
    @           0x4091d9  _start
    @              (nil)  (unknown)
Aborted (core dumped)
`

**Comment by GloriaLovera** [comment]
Some layers shape depends on number of classes. This error is raised because of your number of classes is different from the one of the pretrained model (which is 21 since shape[0] is nr_of_classes*4 for conv_4_3). Are you refining a retrained VOC model? If yes, you should rename every layer which shape depends on the number of classes(e.g. by appending "_new".
Every time you provide a retrained model using -snapshot or -weights parameter caffe checks layers names of the pretrained model and of yours, if two layers has the same name it uses the weights of the pretrained model to initialise your own model but layers shapes must match. 
If you, for instance add "_new" at the end of your layer, names will be different and you won't inherit weights from the retrained model for the renamed layers (which is correct since they depends on the classes number).

**Comment by EvergreenHZ** [comment]
Thank you for your time and your answer. I've already solved the problem
